[package]
name = "daydream_mouse"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.6"
enigo = "0.3.0"
futures-util = "0.3.31"
tokio = { version = "1", features = ["full"] }
uuid = "1.11.0"
